---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keda-component
  namespace: default
spec:
  interval: 10m0s
  url: https://sundarok.github.io/keda-component
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-component
  namespace: default
spec:
  chart:
    spec:
      chart: keda-component
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keda-component
      version: {{ .Values.keda.version | quote }}
  interval: 10m0s
  values: {{ toYaml .Values.keda.values | nindent 4 }}
