---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: keda-component-github
  namespace: default
spec:
  interval: 1m
  ref:
    branch: main
    # tag: v0.1.0
  url: https://github.com/sundarok/keda-component.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-component-helm
  namespace: default
spec:
  chart:
    spec:
      chart: .
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: keda-component-github
  interval: 10m0s
